In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("bollywood_data.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df.sort_values('Year')

,Actor,Film,Year,Genre,BoxOffice(INR crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [5]:
df.sort_values("Year" , ascending=False)

,Actor,Film,Year,Genre,BoxOffice(INR crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [6]:
df2 = df.sort_values(["Year" , "IMDb"] , ascending=False).copy()

# year wise descending first , if year is same then descending the IMDb

In [7]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [8]:
df2.reset_index(drop = True , inplace=True)                    # drop function use to drop the "Index" column
                                                               # inplace: save the change in original dataframe

In [9]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,Hrithik Roshan,War,2019,Action,475,6.5
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [10]:
# df2.sort_index()                          # sort the dataset by index

In [11]:
df2["Rank"] = df2["IMDb"].rank(ascending= False , method="dense")

# method = "dense" : give the same rank if condition is equal for some value

In [12]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
5,Hrithik Roshan,War,2019,Action,475,6.5,7.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0

In [13]:
df2.rename(columns={"Actor" : "Actor name"})                      # to change the column name
#df2.rename(index={0 : "Supper Star , 1:"Mega star"})             # to change the index name

,Actor name,Film,Year,Genre,BoxOffice(INR crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
5,Hrithik Roshan,War,2019,Action,475,6.5,7.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0

In [14]:
#df2.columns = ["Actor name" , "Movie" , "Year" , "Type" , "Collection" , "Rating" , "Rank"]

# use : change the all column name

In [15]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
5,Hrithik Roshan,War,2019,Action,475,6.5,7.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0

In [16]:
# Re-order the columns

df2 = df2[["Film" , "Actor" , "Genre" , "Year" , "IMDb" ,"BoxOffice(INR crore)" ,"Rank"]]

In [18]:
df2

,Film,Actor,Genre,Year,IMDb,BoxOffice(INR crore),Rank
0,Pathaan,Shah Rukh Khan,Action,2023,7.2,1050,5.0
1,Bhool Bhulaiyaa 2,Kartik Aaryan,Horror Comedy,2022,5.9,266,10.0
2,Brahmastra,Ranbir Kapoor,Fantasy,2022,5.6,431,11.0
3,Uri: The Surgical Strike,Vicky Kaushal,Action,2019,8.2,342,3.0
4,Good Newwz,Akshay Kumar,Comedy,2019,7.0,318,6.0
5,War,Hrithik Roshan,Action,2019,6.5,475,7.0
6,Andhadhun,Ayushmann Khurrana,Thriller,2018,8.3,111,2.0
7,Stree,Rajkummar Rao,Horror Comedy,2018,7.5,180,4.0
8,Padmaavat,Ranveer Singh,Historical,2018,7.0,585,6.0
9,Badrinath Ki Dulhania,Varun Dhawan,Romantic Comedy,2017,6.1,201,8.0
10,Tiger Zinda Hai,Salman Khan,Action,2017,6.0,565,9.0
11,Dangal,Aamir Khan,Biography,2016,8.4,2024,1.0

In [22]:
#You can also move one column to the front:

cols = ["Actor"] + [col for col in df.columns if col != "Actor"]
df2 = df2[cols]

In [23]:
df2

,Actor,Actor,Film,Year,Genre,BoxOffice(INR crore),IMDb
0,Shah Rukh Khan,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Kartik Aaryan,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
2,Ranbir Kapoor,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
3,Vicky Kaushal,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Akshay Kumar,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,Hrithik Roshan,Hrithik Roshan,War,2019,Action,475,6.5
6,Ayushmann Khurrana,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Rajkummar Rao,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
8,Ranveer Singh,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,Varun Dhawan,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
10,Salman Khan,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
11,Aamir Khan,Aamir Khan,Dangal,2016,Biography,2024,8.4